apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
    app: sugartalking
---
# Alternatively, you can create a dedicated namespace:
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sugartalking
#   labels:
#     name: sugartalking
#     app: sugartalking
